version: '3.8'

volumes:
  fru-mongo:

services:
  mongo:
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: fru
      MONGO_INITDB_ROOT_PASSWORD: devsecret
    ports:
      - '27017:27017'
    volumes:
      - 'fru-mongo:/data/db'
  api:
    build:
      context: './api'
      target: 'develop-stage'
    depends_on:
      - 'mongo'
    ports:
      - '8081:8081'
    volumes:
      - './api/src:/app/src'
    command: '/bin/sh -c "yarn watch"'
  client:
    environment:
      VUE_API_URL: http://localhost:8081
    build:
      context: './client'
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - './client/src:/app/src'
      - './client/public:/app/public'
    command: '/bin/sh -c "yarn dev"'
